# Generated by Django 5.1.2 on 2024-11-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_project_first_name_project_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("author", models.TextField()),
                ("num_pages", models.PositiveIntegerField()),
                ("published_date", models.DateField()),
                ("rating", models.IntegerField()),
            ],
        ),
    ]
