# Generated by Django 5.1.2 on 2024-11-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("email", models.TextField()),
                ("phone", models.TextField()),
                ("is_fav", models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
